##ML with probablistic programming 
FROM nvcr.io/nvidia/pytorch:25.01-py3
RUN python --version
RUN pip3 --version

RUN  pip3 install pyro-ppl

#install additional stats tools
RUN pip install "arviz[all]"
RUN pip install seaborn

#author: samuel ahuno
#date: Feb 11 2025
